### ISSUE TITLE
completed streams are marked as not connected

### ISSUE THREAD

**Issue by mannharleen** [benthosdev/benthos#1429]
Refer to documentation [here](https://www.benthos.dev/docs/guides/streams_mode/streams_api/#get-ready), 
"a 503 response is returned along with a message naming the faulty stream".

This is great, however, when dealing with those that are self terminating benthos (incorrectly) considers them as a faulty stream.  e.g.:
- `input: { generate: {..., count: 1} }`

Expectation: benthos should NOT return a 503 for such streams.

**Comment by Jeffail** [comment]
Thanks @mannharleen, should be fixed with: https://github.com/benthosdev/benthos/commit/cd760b63d9f121385c9b89e5b078bbc8e3f38a5e

**Comment by mannharleen** [comment]
@Jeffail  Unfortunately, this does not fix for when benthos is running in stream mode.

Scenario:
```js
POST http://localhost:4195/streams @data
GET http://localhost:4195/uuid-02/ready          <------ still gives a 503

/**
@data = 
uuid-02:
    input:
        generate:
            mapping: 'root = {}'
            count: 1
    output:
        drop: {}
**/
```

### Suggestion: 
Assuming a stream has completed successfully. 
While in the normal (non stream) mode, its ok to return a 200 status on `/ready/` because there is only 1 stream running at a time**, it is not ok to return a 200 for `/<streamID>/ready/` when running in stream mode. I would suggest to return a 404 assuming that benthos stream mode should mark a stream as complete and **remove it**. Removing complete streams would also prevent memory leaks over prolonged usage of the same process.

** this is what you have propsed as par of (cd760b6)[https://github.com/benthosdev/benthos/commit/cd760b63d9f121385c9b89e5b078bbc8e3f38a5e]

**Comment by mannharleen** [comment]
Update:
`GET /<streamid>/ready` while returning 503 is also printing this log message:
```
2022/09/03 14:19:22 http: superfluous response.WriteHeader call from github.com/benthosdev/benthos/v4/internal/stream.New.func2 (type.go:57)
```

**Comment by Jeffail** [comment]
Yeah I've updated the individual `/<streamid>/ready` to return a 404 when it's stopped: https://github.com/benthosdev/benthos/commit/006d7bcce045df80f2734f988b5ce781404c35a7

> I think you tried to test it here, not sure why your tests passed

Let me know if you're able to create a test that reproduces it and I'll take another look.

**Comment by mannharleen** [comment]
@Jeffail working as expected now.
However, I am reconsidering amending my suggestion now: 
While a a stream that has finished does return a 404 now for `/<streamid>/ready`,
a stream that never existed also return a 404 (as it always was) : `/<invalidStreamId>/ready`

Updated suggestion: Instead of 404, perhaps we should return a 410 on `/<streamid>/ready` for completed streams. 
As per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410): 
> 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.

seems to suit the purpose.
